[package]
name = "timers"
version = "0.1.0"
description = "Timers desktop application"
authors = ["github.com/kubasovp"]
edition = "2021"

[lib]
name = "timers_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.11.4", features = [] }
tauri-plugin-notification = "2.3.3"
tauri-plugin-os = "2.3.2"
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }
